### ISSUE TITLE
书籍翻译分工安排

### ISSUE THREAD

**Issue by will-ww** [OpenEduTech/AccelerateDevOps#1]
欢迎大家认领相关章节：

电子版（仅内部）：参见这里面的[语雀链接](https://github.com/X-lab2017/open-wonderland/discussions/209)

**第一部分 精益研发管理与协作**（140p）

- [x] 1. Chapter 1, Metrics That Matter（@soobun）
- [x] 2. Chapter 2, Plan, Track, and Visualize Your Work （@19883235 ）
- [x] 3. Chapter 3, Teamwork and Collaborative Development （@lhbvvvvv）
- [x] 4. Chapter 4, Asynchronous Work: Collaborate from Anywhere（@veronipp）
- [x] 5. Chapter 5, Influence of Open and Inner Source on Software Delivery Performance（@Zzzzzhuzhiwei）

**第二部分 DevOps 工程实践**（120p）

- [x] 6. Chapter 6, Automation with GitHub Actions（@yfsn666）
- [x] 7. Chapter 7, Running Your Workflows（@shijilin0116）
- [x] 8. Chapter 8, Managing Dependencies Using GitHub Packages（@Laceyoo）
- [x] 9. Chapter 9, Deploy to Any Platform（@Goinggoinggoing）
- [x] 10. Chapter10, Feature Flags and the Feature Lifecycle（@shijilin0116）
- [x] 11. Chapter 11, Trunk-Based Development（@Laceyoo）

**第三部分 安全可信的发布**（100p）

- [x] 12. Chapter 12, Shift Left Testing for Increased Quality（@Miaheeee）
- [x] 13. Chapter 13, Shift Left Security and DevSecOps（@LPY22）
- [x] 14. Chapter 14, Securing Your Code（@huaowei）
- [x] 15. Chapter 15, Securing Your Deployments（@xunx911）

**第四部分 软件架构**（24p）

- [x] 16. Chapter 16, Loosely Coupled Architecture and Microservices（@andyhuang18）
- [x] 17. Chapter 17, Empower Your Teams（@andyhuang18）

**第五部分 精益产品管理**（30p）

- [x] 18. Chapter 18, Lean Product Development and Lean Startup（@YuxinLi1 )
- [x] 19. Chapter 19, Experimentation and A|B-Testing （@YuxinLi1 )

**第六部分 面向企业的 GitHub**（56p）

- [x] 20. Chapter 20, GitHub: The Home for All Developers（@wj23027）
- [x] 21. Chapter 21, Migrating to GitHub（@wj23027）
- [x] 22. Chapter 22, Organize Your Teams（@andyhuang18）
- [x] 23. Chapter 23, Transform Your Enterprise（@Zzzzzhuzhiwei）

**Comment by soobun** [comment]
🙋 Chapter 1: Metrics that Matter

**Comment by andyhuang18** [comment]
Chapter 16, Loosely Coupled Architecture and Microservices

**Comment by wj23027** [comment]
Chapter 21, Migrating to GitHub

**Comment by Zzzzzhuzhiwei** [comment]
Chapter 5, Influence of Open and Inner Source on Software Delivery Performance

**Comment by will-ww** [comment]
Many thanks the above claim, and I have adjust some additional chapters according to the context and workload~ :-)

**Comment by Yuxin61** [comment]
Chapter 19, Experimentation and A|B-Testing

**Comment by 19883235** [comment]
Chapter 2, Plan, Track, and Visualize Your Work

**Comment by Laceyoo** [comment]
Chapter 8, Managing Dependencies Using GitHub Packages

**Comment by shijilin0116** [comment]
🙋 Chapter 7, Running Your Workflows

**Comment by LPY22** [comment]
Chapter 12, Shift Left Testing for Increased Quality

**Comment by will-ww** [comment]
Many thanks the above claim, also adjusted some additional chapters according to the context and workload:
- chapter 7 + chapter 10
- chapter 8 + chapter 11
- Chapter 12 + Chapter 13
- Chapter 18 + Chapter 19

Now, there are 6 chapters left~

**Comment by 19883235** [comment]
Chapter 3, Teamwork and Collaborative Development

**Comment by veronipp** [comment]
Chapter 4, Asynchronous Work: Collaborate from Anywhere

**Comment by yfsn666** [comment]
Chapter 6, Automation with GitHub Actions

**Comment by xunx911** [comment]
Chapter 15, Securing Your Deployments

**Comment by huaowei** [comment]
Chapter 14, Securing Your Code

**Comment by Goinggoinggoing** [comment]
Chapter 9, Deploy to Any Platform

**Comment by will-ww** [comment]
> Chapter 3, Teamwork and Collaborative Development

As you have claimed Chapter 2 which more than 30 pages, I suggest leave this chapter to others. Anyway, many thanks~ @19883235
